### ISSUE TITLE
Add Yinyang K-Means?

### ISSUE THREAD

**Issue by findmyway** [PyDataBlog/ParallelKMeans.jl#43]
- [paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/ding15.pdf)
- [code](https://github.com/src-d/kmcuda)

**Comment by PyDataBlog** [comment]
@findmyway thanks for the suggestion. We have now added it to the project's Wiki.

**Comment by Arkoniak** [comment]
@findmyway thank you for this reference, this algorithm is really amazing and will be merged soon.

Do you know the intrinsic of this algorithm implementation? I wasn't able to figure out where "so-far-found second closest center" is coming from. I am referring step 3.3 "For each remaining point x, filter its remaining candidate centers with the so-far-found second closest center". So, current implementation is somewhat different, in that I apply local filtering, using the nearest known center, but still update whole group (double local filtering). My experiments showed that second local filtering is rather fast.

**Comment by findmyway** [comment]
Hi @Arkoniak , it's amazing that you come up with the implementation in such a short time!

I just read the paper again to refresh my understanding of it. In the *Local Filtering* step, we already a point **x** and the groups  passed from *Global Filtering*. Now we can do something like this to avoid calculating some distances:

```julia
cur_nearest_center = centers[1]
cur_second_nearest_center = centers[2]
if distance(x, cur_second_nearest_center) <= distance(x, cur_nearest_center)
    cur_nearest_center, cur_second_nearest_center = cur_second_nearest_center, cur_nearest_center
end

for c in centers[3:end]
    if !filtered_by_lemma2(c, cur_second_nearest_center)
        distance_c =  distance(x, c)
        # update distances and maintain cur_second_nearest_center
    end
end
```
Note that I've never implemented this algorithms before. So feel free to correct me if I'm wrong😀. 
Again, this project is really awesome!

**Comment by PyDataBlog** [comment]
@Arkoniak #67 closes this issue. @findmyway please close this issue upon the release of `0.1.5`. Feel free to re-open for optimizations tips for the implementation.

**Comment by findmyway** [comment]
🎉🎉 🎉

**Comment by Arkoniak** [comment]
For future references (in case this issue arise again, it was really complicated for me and I always forget what was the obstacles).

As I understood, main idea was that if you are in _LocalFiltering_ step, then you should update lower bound properly (you shouldn't waste calculated distances). Yet at the same time, it's easy to show an example, that it is impossible to determine proper lower bound with filtered data only!

![2020-04-24 11-51-03](https://user-images.githubusercontent.com/2630519/80218283-a825b700-8649-11ea-8650-02c165cdd9c7.jpeg)

(Sorry for the bad quality)

On the left our situation before calculations. We know some upper bound, some lower bound (determined at the previous step) and some drifts. One can also think, for simplicity, that we somehow know positions before drift, so we can assess the situation. From this picture it's obvious that the point `c3`  will be filtered out, since it's drift is too small.

But after we update distances to not filtered centers `c1`, `c2`, lower bound will increase, since they are moving outwards. Yet, at the same time if we wouldn't filter centers, we find out that lower bound became smaller, since `c2` drifted inwards.

I've spent a lot of time thinking about this situation and I can't understand how to update properly lower bound only be looking at remaining centers. So in my implementation, I do it in two passes:
1. Update upper bound for all not filtered centers. Also determine temporary new lower bound 
2. Update lower bound on all previously filtered centers whose drift is large enough to cross new lower bound.

Actually it's not as frightening as it seems, since in my experiments only small fraction of centers satisfy second condition (they gave something like +15%-20% increase to all distances calculated in step 1).
